FROM maven:3.8.3-jdk-8 as mavenbuild
WORKDIR /package
COPY . .
RUN mvn clean package
FROM tomcat:8.0.20-jre8
COPY --from=mavenbuild /package/target/*.war /usr/local/tomcat/webapps/petclinic.war
CMD ["catalina.sh", "run"]
EXPOSE 8080
